#' Placebo Test Using Fake Treatment Unit
#'
#' \code{placebo_unit} is the function of doing placebo test by using fake treatment units to see
#'  if the treatment effect we got using real treatment unit is the largest, in other words, we are expecting
#'  to see the fake treatemt unit will induce smaller delta.
#'
#' @param result The object generated by the \code{\link{draw_donorpool}}.
#' @param lead_period how many time points in advance of the real treatment time we want to test.
#'  For example, if the real treatment time is t, and we want to test t - 1, t - 2, t - 3,
#'  we could set the lead_period = 3
#'
#' @return The ggplot object visualizing the placebo test using fake treatment time
placebo_unit <-  function(result) {
  # we get the members of donor pool in the results as the fake treatment unit
  unit_list <- result$Donor_Pool_Result %>%
    rownames_to_column("unit") %>%
    filter(unit != "(Intercept)") %>%
    pull(unit) %>%
    c(result$target_name)

  placebo_plot_result <- foreach(i = 1:length(unit_list), .combine = rbind) %do% {
    placebo_result <- draw_donorpool(data = result$data, target_name = unit_list[i], donorpool_name = result$donorpool_name,
                                     time_name = result$time_name, period = result$period, nvmax = result$nvmax)

    # Gather the actural and counterfactual value
    delta_result <- placebo_result$Simulation_Result %>%
      mutate(delta = y_sim - y_actural) %>%
      # Generate a group label
      mutate(treatment_unit = unit_list[i])

    return(delta_result)
  } %>%
    rename(`Treatment Unit` = treatment_unit)

  # Generate the name of time variable that indicated the real after treatment period
  period_min <- placebo_plot_result %>%
    filter(`Treatment Unit` == result$target_name) %>%
    filter(treatment_dummy == 1) %>%
    select(time) %>%
    head(1) %>%
    .[1,1]

  period_max <- placebo_plot_result %>%
    filter(`Treatment Unit` == result$target_name) %>%
    filter(treatment_dummy == 1) %>%
    select(time) %>%
    tail(1) %>%
    .[1,1]

  # Prepare the data for figure
  real_placebo_plot_result <- placebo_plot_result %>%
    filter(`Treatment Unit` == result$target_name)

  # Plot the figure
  plot_placebo_unit_object <- placebo_plot_result %>%
    ggplot() +
    annotate("rect", xmin = period_min, xmax = period_max,
             ymin = -Inf, ymax = Inf,
             fill = "grey", colour = "grey", alpha = 0.4) +
    geom_hline(yintercept = 0, linetype = "dashed",
               color = "red") +
    geom_point(aes(time, delta, group = `Treatment Unit`, color = `Treatment Unit`), alpha = 0.4) +
    geom_line(aes(time, delta, group = `Treatment Unit`, color = `Treatment Unit`), alpha = 0.4) +
    geom_point(aes(time, delta, group = `Treatment Unit`, color = `Treatment Unit`), data = real_placebo_plot_result, size = 2) +
    geom_line(aes(time, delta, group = `Treatment Unit`, color = `Treatment Unit`), data = real_placebo_plot_result, size = 1.2) +
    xlab("Time") +
    ylab("Difference between Counterfactual and Actual Value") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))

  return(plot_placebo_unit_object)
}

# placebo_time(result, 3)
