#' Visualization of the difference between the simulated counterfactual and actural value.
#'
#' \code{plot_delta} is the visualization of the difference between the simulated counterfactual
#' (generated by \code{\link{draw_donorpool}}) and actural value.
#'
#' @param result The object generated by the \code{\link{draw_donorpool}}.
#'
#' @return The ggplot object visualizing the delta.
#' @importFrom magrittr "%>%"
#' @importFrom foreach "%do%"
#' @export
plot_delta <- function(result) {
  # First generate the treatment period variables
  period_min <- result$Simulation_Result %>%
    dplyr::filter(treatment_dummy == 1) %>%
    dplyr::select(time) %>%
    head(1) %>%
    .[1,1]

  period_max <- result$Simulation_Result %>%
    dplyr::filter(treatment_dummy == 1) %>%
    dplyr::select(time) %>%
    tail(1) %>%
    .[1,1]

  # Gather the actural and counterfactual value
  delta_result <- result$Simulation_Result %>%
    dplyr::mutate(delta = y_sim - y_actural)

  # Plot the figure
  plot_delta_object <- delta_result %>%
    ggplot2::ggplot(ggplot2::aes(time, delta)) +
    ggplot2::annotate("rect", xmin = period_min, xmax = period_max,
             ymin = -Inf, ymax = Inf,
             fill = "grey", colour = "grey", alpha = 0.4) +
    ggplot2::geom_hline(yintercept = 0, linetype = "dashed",
               color = "red") +
    ggplot2::geom_point() +
    ggplot2::geom_line(ggplot2::aes(group = 1)) +
    ggplot2::xlab("Time") +
    ggplot2::ylab("Difference between Counterfactual and Actual Value") +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))

  return(plot_delta_object)
}
